### PR TITLE
bluesky and ophyd0 upgrade

### PR DESCRIPTION
**Pull request by klauer**
Too many changes to list

### CODE REVIEW

**Comment by ericdill** [comment]
oh lawd merge conflicts on this PR :fearful:

**Comment by klauer** [comment]
Yeah, uhh, I think this will be a force push and the old version can be moved to a different branch. I touched probably every line during the upgrade...

**Comment by ericdill** [comment]
```
$ git merge klauer/ophyd0
Removing hxntools/uid_broadcast.py
CONFLICT (modify/delete): hxntools/spiral_scans.py deleted in klauer/ophyd0 and modified in HEAD. Version HEAD of hxntools/spiral_scans.py left in tree.
Removing hxntools/scan_patterns.py
Auto-merging hxntools/scan_info.py
Auto-merging hxntools/detectors/merlin.py
CONFLICT (content): Merge conflict in hxntools/detectors/merlin.py
Removing hxntools/detectors/master_detector.py
Automatic merge failed; fix conflicts and then commit the result.
```

diff is:

``` diff
diff --cc hxntools/detectors/merlin.py
index f759838,fcc4556..0000000
--- a/hxntools/detectors/merlin.py
+++ b/hxntools/detectors/merlin.py
@@@ -12,122 -13,26 +13,127 @@@ import filestore.api as fsap

  logger = logging.getLogger(__name__)

+ # blocking_callbacks.put(1)   # <-- not set, unsure if necessary
+ # num_capture.put(self._total_points)  # <-- set to 0

++<<<<<<< HEAD
 +class MerlinFileStore(AreaDetectorFSIterativeWrite):
 +    def __init__(self, det, basename, **kwargs):
 +        super(MerlinFileStore, self).__init__(basename, cam='cam1:',
 +                                              **kwargs)
 +
 +        self._det = det
 +        self._file_plugin = None
 +        self._plugin = det.tiff1
 +        self.file_template = '%s%s_%6.6d.tiff'
 +        self._file_template = self._plugin.file_template
 +        self._master = None
 +
 +        # NOTE: hack to get parent classes to work...
 +        # NOTE: areadetector array sizes were rearranged to mirror numpy indexing
 +        #       so they differ from what AreaDetectorFSIterativeWrite expects
 +        self._arraysize0 = self._plugin.array_size.signals[1]
 +        self._arraysize1 = self._plugin.array_size.signals[0]
 +        self._external_trig = False
 +
 +    def _insert_fs_resource(self):
 +        return fs.insert_resource('AD_TIFF', self._store_file_path,
 +                                  {'template': self._file_template.value,
 +                                   'filename': self._filename,
 +                                   'frame_per_point': 1})
 +
 +    def read(self):
 +        ret = super(MerlinFileStore, self).read()
 +        lightfield_key = '{}_image_lightfield'.format(self._det.name)
 +        return {self._det.name: ret[lightfield_key]}
 +
 +    def bulk_read(self, timestamps):
 +        uids = list(str(uuid.uuid4()) for ts in timestamps)
 +        datum_args = (dict(point_number=i) for i in range(len(uids)))
 +        bulk_insert_datum(self._filestore_res, uids, datum_args)
 +        return {self._det.name: uids}
 +
 +    def describe(self):
 +        size = (self._arraysize1.value,
 +                self._arraysize0.value)
 +
 +        return {self._det.name: {'external': 'FILESTORE:',
 +                                 'source': 'PV:{}'.format(self._basename),
 +                                 'shape': size, 'dtype': 'array'}
 +                }
 +
 +    def configure(self, state=None):
 +        super(MerlinFileStore, self).configure(state=state)
 +        ext_trig = (self._master is not None or self._external_trig)
 +
 +        det = self._det
 +        plugin = self._plugin
 +
 +        # self._image_mode.put(0, wait=True)
 +        plugin.blocking_callbacks.put(1)
 +        plugin.file_template.put(self.file_template, wait=True)
 +        self._make_filename()
 +        plugin.file_path.put(self._ioc_file_path, wait=True)
 +        plugin.file_name.put(self._filename, wait=True)
 +        plugin.file_number.put(0)
 +
 +        det.array_callbacks.put('Enable')
 +        # NOTE: recently transform has been used
 +        det.trans1.enable.put(1)
 +
 +        if ext_trig:
 +            if self._total_points is None:
 +                raise RuntimeError('set was not called on this detector')
 +
 +            det.num_images.put(self._total_points)
 +            det.image_mode.put('Multiple')
 +            det.trigger_mode.put('External')
 +            # NOTE: these values specify a debounce time for external
 +            #       triggering so they should be set to < 0.5 the expected
 +            #       exposure time
 +            det.acquire_time.put(0.005)
 +            det.acquire_period.put(0.006)
 +        else:
 +            det.num_images.put(1)
 +            det.image_mode.put('Single')
 +            det.trigger_mode.put('Internal')
 +
 +        plugin.auto_increment.put(1)
 +        plugin.auto_save.put(1)
 +        plugin.num_capture.put(self._total_points)
 +        plugin.file_write_mode.put('Stream')
 +        # plugin.file_write_mode.put('Single')
 +        plugin.enable.put(1)
 +        plugin.capture.put(1)
 +
 +        # print('** Please ensure Merlin is in external triggering (LVDS) '
 +        #       'mode **', file=sys.stderr)
 +        # # NOTE: this is not supported by the ascii protocol (and hence the
 +        # #       EPICS IOC) for some reason
 +        # switching timepix TTL to this for now
 +        self._filestore_res = self._insert_fs_resource()
 +
 +        if ext_trig:
 +            det.acquire.put(1, wait=False)
++=======
++>>>>>>> klauer/ophyd0
+ 
+ class MerlinTiffPlugin(TIFFPlugin, FileStoreBulkReadable, FileStoreTIFF,
+                        Device):
+     def mode_external(self):
+         total_points = self.parent.mode_settings.total_points.get()
+         self.stage_sigs[self.num_capture] = total_points
+ 
+     def get_frames_per_point(self):
+         mode = self.parent.mode_settings.mode.get()
+         if mode == 'external':
+             return 1
+         else:
+             return self.parent.cam.num_images.get()

-     def deconfigure(self):
-         super(MerlinFileStore, self).deconfigure()
- 
-         self._total_points = None
-         self._master = None
-         self._det.tiff1.capture.put(0)
- 
-     def _make_filename(self, **kwargs):
-         super(MerlinFileStore, self)._make_filename(**kwargs)
- 
-         makedirs(self._store_file_path)

-     def set(self, total_points=0, external_trig=False, master=None, **kwargs):
-         self._master = master
-         self._total_points = total_points
-         self._external_trig = bool(external_trig)
+ class MerlinDetectorCam(CamBase):
+     pass


  class MerlinDetector(AreaDetector):
```

**Comment by ericdill** [comment]
but yeah force push is def an option. up to you!

**Comment by klauer** [comment]
@ericdill thanks for looking into that - it wasn't as bad as I had thought. Chose the less forceful option in the end 😄

**Pull request merged**
