### PR TITLE
FIX: actually yield from wrapped plans

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by danielballan** [comment]
How did these ever work?

**Comment by klauer** [comment]
My guess is they're still running an old version. You'd need to do a lot of testing to get the API changes from @tacaswell working, I have a feeling...

**Comment by tacaswell** [comment]
I broke these in #12 (58a8038809cfc2242e5829893d133242585b945b) but they used the old version last cycle and SRX does not use these plans.

**Comment by danielballan** [comment]
👏

**Pull request merged**
